mappings = {
    0: '<KEY_NUL>',
    1: '<KEY_UKWN>',
    2: '<KEY_UKWN>',
    3: '<KEY_UKWN>',
    4: '<KEY_UKWN>',
    5: '<KEY_UKWN>',
    6: '<KEY_UKWN>',
    7: '<KEY_UKWN>',
    8: '<KEY_UKWN>',
    9: '<KEY_TAB>',
    10: '<KEY_ENTER>',
    11: '<KEY_UKWN>',
    12: '<KEY_UKWN>',
    13: '<KEY_ENTER>',
    14: '<KEY_UKWN>',
    15: '<KEY_UKWN>',
    16: '<KEY_UKWN>',
    17: '<KEY_UKWN>',
    18: '<KEY_UKWN>',
    19: '<KEY_UKWN>',
    20: '<KEY_UKWN>',
    21: '<KEY_UKWN>',
    22: '<KEY_UKWN>',
    23: '<KEY_UKWN>',
    24: '<KEY_UKWN>',
    25: '<KEY_UKWN>',
    26: '<KEY_UKWN>',
    27: '<KEY_ESCAPE>',
    28: '<KEY_UKWN>',
    29: '<KEY_UKWN>',
    30: '<KEY_UKWN>',
    31: '<KEY_UKWN>',
    127: '<KEY_BACKSPACE>',
}

